version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/rails"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
